config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  authenticated :user, ->(u) { u.admin? && u.approved? } do
    namespace :admin do
      get 'index'
      get 'approve_requests', to: 'admin#approve_requests'
      get 'database-test', to: 'admin#test'
      post 'fetch_class_info', to: 'admin#fetch_class_info'
    end
  end

  get 'admin/approve_requests'
  get 'approve_requests', to: 'admin#approve_requests'

  get 'home/index'

  get 'sections_for_course/:course_id', to: 'sections#sections_for_course', as: 'sections_for_course'

  resources :courses do
    collection do
      get 'reload_courses'
      post 'do_reload_courses'
    end

    resources :sections, only: [:index, :show, :edit, :update] do
      member do
        get 'view_graders'
      end
    end
  end

  resources :grader_applications do
    member do
      patch 'approve'
    end
  end

  resources :recommendations, only: [:new, :create, :index]

  match '*unmatched', to: 'errors#not_found', via: :all
end

app/models/grader_application.rb
class GraderApplication < ApplicationRecord
  belongs_to :user
  belongs_to :course
  belongs_to :section

  validates :display_name, :first_name, :middle_name, :last_name, :legal_last_name,
            :username, :email, :address, :phone, presence: true

  def full_name
    [first_name, middle_name, last_name, name_suffix].reject(&:blank?).join(' ')
  end
end

app/controllers/grader_applications_controller.rb
class GraderApplicationsController < ApplicationController
  include Pagy::Backend
  before_action :authenticate_user!
  before_action :authorize_admin_or_instructor!, only: [:approve]
  before_action :authorize_student!, only: [:index, :show, :new, :edit, :destroy]

  def index
    if current_user.admin? || current_user.instructor?
      @pagy, @grader_applications = pagy(GraderApplication.all)
    elsif current_user.student?
      @pagy, @grader_applications = pagy(GraderApplication.where(user_id: current_user.id))
    end
    @grader_application = GraderApplication.new
  end

  def show
    @grader_application = GraderApplication.find(params[:id])
  end

  def new
    @grader_application = GraderApplication.new
  end

  def create
    @grader_application = GraderApplication.new(grader_application_params)
    @grader_application.user = current_user

    if @grader_application.save
      redirect_to @grader_application, notice: 'Grader Application was successfully created.'
    else
      render :new
    end
  end

  def edit
    @grader_application = GraderApplication.find(params[:id])
  end

  def update
    @grader_application = GraderApplication.find(params[:id])
    if @grader_application.update(grader_application_params)
      redirect_to @grader_application, notice: 'Grader Application was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @grader_application = GraderApplication.find(params[:id])
    @grader_application.destroy
    redirect_to grader_applications_url, notice: 'Grader Application was successfully destroyed.'
  end

  def approve
    @grader_application = GraderApplication.find(params[:id])
    @grader_application.update(approved: !@grader_application.approved)
    @status_message = @grader_application.approved ? "Application approved successfully." : "Application unapproved successfully."

    respond_to do |format|
      format.html { redirect_to grader_applications_path, notice: @status_message }
      format.js   # This will render `approve.js.erb`
    end
  end

  private

  def grader_application_params
    params.require(:grader_application).permit(:display_name, :first_name, :middle_name, :last_name, :legal_last_name, :name_suffix, :username, :email, :address, :phone, :course_id, :section_id)
  end

  def authorize_admin_or_instructor!
    unless current_user.admin? || current_user.instructor?
      redirect_to root_path, alert: 'You are not authorized to view this page.'
    end
  end

  def authorize_student!
    if current_user.student? && !%w[index show new edit destroy].include?(action_name)
      redirect_to root_path, alert: 'You are not authorized to perform this action.'
    end
  end
end

app/helpers/grader_applications_helper.rb
module GraderApplicationsHelper
end

app/views/grader_applications/_form.html.erb
<%= form_with(model: grader_application, local: true) do |form| %>
  <% if grader_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grader_application.errors.count, "error") %> prohibited this grader_application from being saved:</h2>

      <ul>
      <% grader_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :display_name %>
    <%= form.text_field :display_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :legal_last_name %>
    <%= form.text_field :legal_last_name %>
  </div>

  <div class="field">
    <%= form.label :name_suffix %>
    <%= form.text_field :name_suffix %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.collection_select :course_id, Course.all, :id, :course_name, prompt: 'Select a Course' %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.collection_select :section_id, Section.all, :id,

app/views/grader_applications/approve.js.erb
<% if @grader_application.approved %>
  $("#approved-<%= @grader_application.id %>").text("Yes");
  $("a[href='#{approve_grader_application_path(@grader_application)}']").text("Unapprove");
<% else %>
  $("#approved-<%= @grader_application.id %>").text("No");
  $("a[href='#{approve_grader_application_path(@grader_application)}']").text("Approve");
<% end %>

$("#section-<%= @grader_application.section_id %>-grader-count").text('<%= @grader_application.section.grader_applications.where(approved: true).count %> / <%= @grader_application.section.max_graders %>');

app/views/grader_applications/edit.html.erb
<%= form_with model: @grader_application, local: true do |form| %>
  <% if @grader_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grader_application.errors.count, "error") %> prohibited this application from being saved:</h2>
      <ul>
        <% @grader_application.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :display_name %>
        <%= form.text_field :display_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :middle_name %>
        <%= form.text_field :middle_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :legal_last_name %>
        <%= form.text_field :legal_last_name, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :name_suffix %>
        <%= form.text_field :name_suffix, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :username %>
        <%= form.text_field :username, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :phone %>
        <%= form.telephone_field :phone, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :course_id, 'Select Course' %>
    <%= form.collection_select :course_id, Course.all, :id, :course_name, { prompt: 'Select a Course' }, { class: 'form-select', id: 'course_select' } %>
  </div>

  <div class="form-group">
    <%= form.label :section_id, 'Select Section' %>
    <%= form.collection_select :section_id, [], :id, :section_number, { prompt: 'Select a Section' }, { class: 'form-select', id: 'section_select' } %>
  </div>

  <div class="form-group mt-3">
    <%= form.submit 'Update Application', class: 'btn btn-primary' %>
  </div>
<% end %>

<%= link_to 'Back to Applications', grader_applications_path, class: 'btn btn-secondary mt-3' %>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const courseSelect = document.getElementById('course_select');
    const sectionSelect = document.getElementById('section_select');

    courseSelect.addEventListener('change', function () {
      const courseId = this.value;

      if (courseId) {
        fetch(`/sections_for_course/${courseId}`)
          .then(response => response.json())
          .then(data => {
            sectionSelect.innerHTML = '';

            const promptOption = document.createElement('option');
            promptOption.value = '';
            promptOption.text = 'Select a Section';
            sectionSelect.appendChild(promptOption);

            data.forEach(section => {
              const option = document.createElement('option');
              option.value = section.id;
              option.text = section.section_number;
              sectionSelect.appendChild(option);
            });
          })
          .catch(error => console.error('Error fetching sections:', error));
      } else {
        sectionSelect.innerHTML = '';
      }
    });
  });
</script>

app/views/grader_applications/index.html.erb
<% content_for :title, 'Grader Applications' %>
<div class="admin-content">
  <h1>Grader Applications</h1>
  <div class="d-flex justify-content-end mb-3">
    <% if current_user.student?  %>
      <%= link_to 'New Submission', new_grader_application_path, class: 'btn btn-success btn-sm' %>
    <% end %>
  </div>
  <div class="table-responsive">
    <table class="table" style="color: white;">
      <thead class="thead-dark">
        <tr>
          <th>Display Name</th>
          <th>Full Name</th>
          <th>Email</th>
          <th>Course</th>
          <th>Section</th>
          <th>Approved</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @grader_applications.each do |application| %>
          <tr id="application-<%= application.id %>">
            <td><%= application.display_name %></td>
            <td><%= "#{application.first_name} #{application.middle_name} #{application.last_name}" %></td>
            <td><%= application.email %></td>
            <td><%= application.course.course_name if application.course %></td>
            <td><%= application.section.section_number if application.section %></td>
            <td id="approved-<%= application.id %>"><%= application.approved ? 'Yes' : 'No' %></td>
            <td class="d-flex align-items-center">
              <%= link_to 'Show', grader_application_path(application), class: 'btn btn-info btn-sm me-2' %>
              <% if current_user.student? && current_user == application.user %>
                <%= link_to 'Edit', edit_grader_application_path(application), class: 'btn btn-primary btn-sm me-2' %>
                <%= link_to 'Delete', grader_application_path(application), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm me-2' %>
              <% elsif current_user.admin? || current_user.instructor? %>
                <%= button_to application.approved ? 'Unapprove' : 'Approve', approve_grader_application_path(application), method: :patch, remote: true, class: 'btn btn-warning btn-sm', id: "approve-button-#{application.id}" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="pagination">
  <%= raw pagy_nav(@pagy) %>
</div>

app/views/grader_applications/new.html.erb
<h1>New Grader Application</h1>

<%= form_with model: @grader_application, local: true do |form| %>
  <% if @grader_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grader_application.errors.count, "error") %> prohibited this application from being saved:</h2>
      <ul>
        <% @grader_application.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-content">
    
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :display_name %>
        <%= form.text_field :display_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :middle_name %>
        <%= form.text_field :middle_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :legal_last_name %>
        <%= form.text_field :legal_last_name, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :name_suffix %>
        <%= form.text_field :name_suffix, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :username %>
        <%= form.text_field :username, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :phone %>
        <%= form.telephone_field :phone, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :course_id, 'Select Course' %>
    <%= form.collection_select :course_id, Course.all, :id, :course_name, { prompt: 'Select a Course' }, { class: 'form-select' } %>
  </div>

  <div class="form-group">
    <%= form.label :section_id, 'Select Section' %>
    <%= form.collection_select :section_id, Section.all, :id, :section_number, { prompt: 'Select a Section' }, { class: 'form-select' } %>
  </div>

  <div class="form-group mt-3">
    <%= form.submit 'Submit Application', class: 'btn btn-primary' %>
  </div>
</div>
  
<% end %>

<%= link_to 'Back to Applications', grader_applications_path, class: 'btn btn-secondary mt-3' %>

app/views/grader_applications/show.html.erb
<% content_for :title, 'Application Details' %>
<div class="admin-content">
  <h1>Application Details</h1>
  
  <div class="table-responsive">
    <table class="table" style="color: white;">
      <tbody>
        <tr>
          <th>Display Name</th>
          <td><%= @grader_application.display_name %></td>
        </tr>
        <tr>
          <th>First Name</th>
          <td><%= @grader_application.first_name %></td>
        </tr>
        <tr>
          <th>Middle Name</th>
          <td><%= @grader_application.middle_name %></td>
        </tr>
        <tr>
          <th>Last Name</th>
          <td><%= @grader_application.last_name %></td>
        </tr>
        <tr>
          <th>Legal Last Name</th>
          <td><%= @grader_application.legal_last_name %></td>
        </tr>
        <tr>
          <th>Name Suffix</th>
          <td><%= @grader_application.name_suffix %></td>
        </tr>
        <tr>
          <th>Username</th>
          <td><%= @grader_application.username %></td>
        </tr>
        <tr>
          <th>Email</th>
          <td><%= @grader_application.email %></td>
        </tr>
        <tr>
          <th>Address</th>
          <td><%= @grader_application.address %></td>
        </tr>
        <tr>
          <th>Phone</th>
          <td><%= @grader_application.phone %></td>
        </tr>
        <tr>
          <th>Course</th>
          <td><%= @grader_application.course.course_name if @grader_application.course %></td>
        </tr>
        <tr>
          <th>Section</th>
          <td><%= @grader_application.section.section_number if @grader_application.section %></td>
        </tr>
      </tbody>
    </table>
  </div>
  
  <div class="d-flex justify-content-between mt-3">
    <% if user_signed_in? && (current_user == @grader_application.user || current_user.admin?) %>
      <%= button_to 'Delete Application', @grader_application, method: :delete, data: { confirm: 'Are you sure you want to delete this application?' }, class: 'btn btn-danger' %>
    <% end %>
    <%= link_to 'Back to Applications', grader_applications_path, class: 'btn btn-secondary' %>
  </div>
</div>