config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  authenticated :user, ->(u) { u.admin? && u.approved? } do
    namespace :admin do
      get 'index'
      get 'approve_requests', to: 'admin#approve_requests'
      get 'database-test', to: 'admin#test'
      post 'fetch_class_info', to: 'admin#fetch_class_info'
    end
  end

  get 'admin/approve_requests'
  get 'approve_requests', to: 'admin#approve_requests'

  get 'home/index'

  get 'sections_for_course/:course_id', to: 'sections#sections_for_course', as: 'sections_for_course'

  resources :courses do
    collection do
      get 'reload_courses'
      post 'do_reload_courses'
    end

    resources :sections, only: [:index, :show, :edit, :update] do
      member do
        get 'view_graders'
      end
    end
  end

  resources :grader_applications do
    member do
      patch 'approve'
    end
  end

  resources :recommendations, only: [:new, :create, :index]

  match '*unmatched', to: 'errors#not_found', via: :all
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :verify_admin, only: [:do_reload_courses, :new, :create, :edit, :update, :destroy, :do_reload_courses]

  def fetch_class_info
    term = params[:term]
    campus = params[:campus]
    
    fetcher = FetchClassInfo.new(term: term, campus: campus)
    
    if fetcher.call
      flash[:notice] = "Class information imported successfully."
    else
      flash[:alert] = "There was an error importing class information."
    end
    
    redirect_to admin_courses_path
  end

  def index
    if params[:search].present?
      search_term = params[:search].downcase
      @courses = Course.search(search_term)
      if @courses.empty?
        flash.now[:notice] = "There are no courses found for these params."
        @pagy, @courses = pagy(Course.none, items: 10)
      else
        @pagy, @courses = pagy(@courses, items: 10)
      end
    else
      @pagy, @courses = pagy(Course.all, items: 10)
    end

    if params[:sort_by] == 'name'
      @courses = @courses.order(course_name: :asc)
    elsif params[:sort_by] == 'date'
      @courses = @courses.order(created_at: :desc)
    end

    @pagy, @courses = pagy(@courses, items: 10)
  end

  def show
    @course = Course.includes(sections: :meetings).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Sorry! Course not found"
    redirect_to courses_path
  end

  def new
    @course = Course.new
  end

  def edit
    @course = Course.includes(sections: :meetings).find(params[:id])
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: "Course successfully created."
    else
      flash.now[:alert] = @course.errors.full_messages.to_sentence
      render 'new'
    end
  rescue ActionController::ParameterMissing => e
    @course = Course.new
    flash.now[:alert] = "Please fill in all required fields."
    render 'new'
  end

  def update
    @course = Course.find(params[:id])
    
    if @course.update(course_params)
      flash[:notice] = "Success! See below for your updated course!"
      redirect_to course_path(@course, search: params[:search], sort_by: params[:sort_by])
    else
      flash.now[:alert] = @course.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url(search: params[:search], sort_by: params[:sort_by]), notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def reload_courses
  end

  def do_reload_courses
    term = params[:term]
    campus = params[:campus]
  
    if term.present? && campus.present?

      GraderApplication.delete_all
      Recommendation.delete_all

      Meeting.delete_all
      Section.delete_all
      Course.delete_all
  
      if call_fetch_class_info(term, campus)
        flash[:notice] = "Class information imported successfully."
      else
        flash[:alert] = "There was an error importing class information."
      end
    else
      flash[:alert] = "Term and campus are required to reload courses."
    end
    redirect_to courses_path
  end
  
  private

  def course_params
    params.require(:course).permit(
      :course_number, :course_name, :course_description, :credits, 
      :term, :effective_date, :effective_status, :title, :short_description, 
      :equivalent_id, :allow_multi_enroll, :max_units, :min_units, :repeat_units_limit, 
      :grading, :component, :primary_component, :offering_number, :academic_group, 
      :subject, :catalog_number, :campus, :academic_org, :academic_career, :cip_code, 
      :campus_code, :catalog_level, :subject_desc, :course_attributes_json, 
      sections_attributes: [:id, :max_graders, :number_of_graders]
    )
  end

  def call_fetch_class_info(term, campus)
    fetcher = FetchClassInfo.new(term: term, campus: campus)

    if fetcher.call
      true
    else
      Rails.logger.error "FetchClassInfo service failed for term: #{term}, campus: #{campus}"
      false
    end
  end

  def verify_admin
    unless current_user.admin?
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to root_path
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with model: @course, local: true do |form| %>
  <%= hidden_field_tag :search, params[:search] %>
  <%= hidden_field_tag :sort_by, params[:sort_by] %>

  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:
      </h2>
      <ul>
        <% @course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :course_number, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :course_number, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :course_name, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :course_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :course_description, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_area :course_description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :credits, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.number_field :credits, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 offset-sm-2">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<% content_for :title, 'Listing courses' %>
<div class="admin-content">
  <h1>Listing courses</h1>
  <div class="header">
    <div></div>
    <% if user_signed_in? && current_user.admin? && current_user.approved? %>
      <%= link_to 'New Course', new_course_path, class: 'btn btn-primary' %>
      <%= link_to 'Reload Courses', reload_courses_courses_path, class: 'btn btn-warning' %>
    <% end %>
  </div>

  <%= form_with url: courses_path, method: :get, local: true do %>
    <div class="form-group">
      <%= label_tag :search, 'Search:' %>
      <%= text_field_tag :search, params[:search], class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag :sort_by, 'Sort by:' %>
      <%= select_tag :sort_by, options_for_select([['Name', 'name'], ['Date', 'date']], selected: params[:sort_by]), prompt: 'Select sort order', class: 'form-control' %>
    </div>
    <%= submit_tag 'Search', class: 'btn btn-primary' %>
  <% end %>

  <div class="table-responsive">
    <table class="table" style="color: white;">
      <thead>
        <tr>
          <th>Name</th>
          <th>Comment</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @courses.each do |course| %>
          <tr>
            <td><%= link_to course.course_name, course_path(course) %></td>
            <td><%= course.course_description %></td>
            <td><%= link_to 'Show', course_path(course), class: 'btn btn-info btn-sm' %></td>
            <% if user_signed_in? && current_user.admin? %>
            <td><%= link_to 'Edit', edit_course_path(course, search: params[:search], sort_by: params[:sort_by]), class: 'btn btn-primary btn-sm' %></td>
              <td>
                <%= form_with(url: course_path(course), method: :delete, local: true) do %>
                  <%= hidden_field_tag :search, params[:search] %>
                  <%= hidden_field_tag :sort_by, params[:sort_by] %>
                  <%= submit_tag 'Delete', data: { confirm: 'Are you sure you want to delete this course?' }, class: 'btn btn-danger btn-sm' %>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="pagination">
  <%= raw pagy_nav(@pagy) %>
</div>

app/views/courses/new.html.erb
<% content_for :title, 'Manage Courses' %>
<div class="admin-content">
  <h1>Manage Courses</h1>

  <%= form_with(model: @course, local: true, html: { class: 'form-horizontal' }) do |form| %>
    <% if @course.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>
        <ul>
          <% @course.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row mb-3">
      <%= form.label :course_number, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= form.text_field :course_number, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= form.label :course_name, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= form.text_field :course_name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= form.label :course_description, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= form.text_area :course_description, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row mb-3">
      <%= form.label :credits, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= form.number_field :credits, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10 offset-sm-2">
        <%= form.submit 'Save', class: 'btn btn-primary' %>
        <%= link_to 'Back to Courses', courses_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/reload_courses.html.erb
<% content_for :title, 'Reload Courses' %>
<h1>Reload Courses</h1>

<%= form_with url: do_reload_courses_courses_path, method: :post, local: true do |form| %>
  <div class="field">
    <%= form.label :term, "Term" %>
    <%= form.select :term, options_for_select([
      ['Spring 2022', '1222'],
      ['Autumn 2022', '1228'],
      ['Spring 2023', '1232'],
      ['Summer 2023', '1234'],
      ['Autumn 2023', '1238'],
      ['Spring 2024', '1242'],
      ['Summer 2024', '1244'],
      ['Autumn 2024', '1248']
    ]) %>
  </div>

  <div class="field">
    <%= form.label :campus, "Campus" %>
    <%= form.select :campus, options_for_select([
      ['Columbus', 'col'],
      ['Lima', 'lma'],
      ['Mansfield', 'mns'],
      ['Marion', 'mrn'],
      ['Newark', 'nwk'],
      ['Wooster', 'wst']
    ]) %>
  </div>

  <div class="actions">
    <%= form.submit "Reload Courses" %>
  </div>
<% end %>

<%= link_to 'Back to Courses', courses_path %>

app/views/courses/show.html.erb
<div class="course-details-container">
  <div class="home-container d-flex justify-content-center align-items-center">
    <div class="admin-content">
      <h1 class="display-4"><%= @course.course_name %></h1>
      <p class="lead"><%= @course.course_description %></p>
      <p class="mb-4">Credits: <%= @course.credits %></p>
      <%= link_to 'Back', courses_path(search: params[:search], sort_by: params[:sort_by]), class: 'btn btn-secondary' %>
      <% if current_user.admin? %>
        <%= link_to 'Edit', edit_course_path(@course, search: params[:search], sort_by: params[:sort_by]), class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

  <div class="sections-container mt-5">
    <h2>Sections</h2>
    <% if @course.sections.any? %>
      <div class="row">
        <% @course.sections.each do |section| %>
          <div class="col-md-6 mb-4">
            <div class="card">
              <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
                <h5 class="card-title mb-0">Section <%= section.section_number %></h5>
                <div>
                  <%= link_to 'View Graders', view_graders_course_section_path(@course, section), class: 'btn btn-light' %>
                  <% if current_user.admin? %>
                    <%= link_to 'Edit Section', edit_course_section_path(@course, section), class: 'btn btn-light' %>
                  <% end %>
                  <span class="badge badge-light"><%= section.grader_applications.where(approved: true).count %> / <%= section.max_graders || 2 %></span>
                </div>
              </div>
              <div class="card-body">
                <p><strong>Instructor:</strong> 
                  <% instructors = section.meetings.flat_map do |meeting| 
                    begin
                      parsed_instructors = meeting.instructors_json.gsub("=>", ":")
                      JSON.parse(parsed_instructors || '[]').map { |i| i['displayName'] }
                    rescue JSON::ParserError
                      []
                    end
                  end.uniq %>
                  <%= instructors.join(", ") %>
                </p>
                <p><strong>Meeting Days:</strong>
                  <% section.meetings.each do |meeting| %>
                    <%= "M" if meeting.monday %>
                    <%= "T" if meeting.tuesday %>
                    <%= "W" if meeting.wednesday %>
                    <%= "R" if meeting.thursday %>
                    <%= "F" if meeting.friday %>
                  <% end %>
                </p>
                <p><strong>Start Time:</strong> <%= section.meetings.first.start_time.strftime("%I:%M %p") if section.meetings.first.start_time %></p>
                <p><strong>End Time:</strong> <%= section.meetings.first.end_time.strftime("%I:%M %p") if section.meetings.first.end_time %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>No sections available for this course.</p>
    <% end %>
  </div>
</div>