config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  authenticated :user, ->(u) { u.admin? && u.approved? } do
    namespace :admin do
      get 'index'
      get 'approve_requests', to: 'admin#approve_requests'
      get 'database-test', to: 'admin#test'
      post 'fetch_class_info', to: 'admin#fetch_class_info'
    end
  end

  get 'admin/approve_requests'
  get 'approve_requests', to: 'admin#approve_requests'

  get 'home/index'

  get 'sections_for_course/:course_id', to: 'sections#sections_for_course', as: 'sections_for_course'

  resources :courses do
    collection do
      get 'reload_courses'
      post 'do_reload_courses'
    end

    resources :sections, only: [:index, :show, :edit, :update] do
      member do
        get 'view_graders'
      end
    end
  end

  resources :grader_applications do
    member do
      patch 'approve'
    end
  end

  resources :recommendations, only: [:new, :create, :index]

  match '*unmatched', to: 'errors#not_found', via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | <%= Rails.application.config.application_name %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

  <style>
    #flash-messages {
      position: fixed;
      top: 10%;
      left: 50%;
      width: 50%;
      z-index: 1050;
      text-align: center;
      transform: translate(-50%, -50%);
    }

    .dropdown-menu {
      z-index: 1060;
    }

    .nav-link {
      margin-right: 15px;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark opacity-75">
    <div class="container">
      <%= link_to Rails.application.config.application_name, root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <% if user_signed_in? && current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'Approve Requests', "/approve_requests", class: 'nav-link' %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Application', grader_applications_path(id: current_user.id), class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Course', courses_path, class: 'nav-link' %>
            </li>
            <% if current_user.admin? || current_user.instructor? %>
              <li class="nav-item">
                <%= link_to 'New Recommendation', new_recommendation_path, class: 'nav-link' %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'View Recommendations', recommendations_path, class: 'nav-link' %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "#{current_user.first_name} #{current_user.last_name}" %>
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><%= link_to 'Change Password', edit_user_registration_path, class: 'dropdown-item' %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div id="flash-messages">
    <% if flash.any? %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
          <%= value %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="container my-5">
    <%= yield %>
  </div>
  <div id="custom-popup" class="custom-popup">
    <span class="close-btn" onclick="document.getElementById('custom-popup').classList.remove('active')">&times;</span>
    <p id="popup-message"></p>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    document.addEventListener('turbolinks:load', () => {
      <% if flash[:notice] %>
        document.getElementById('popup-message').textContent = "<%= j flash[:notice] %>";
        document.getElementById('custom-popup').classList.add('active');
      <% elsif flash[:alert] %>
        document.getElementById('popup-message').textContent = "<%= j flash[:alert] %>";
        document.getElementById('custom-popup').classList.add('active');
      <% end %>
    });
  </script>
</body>
</html>